
import { Product, Category } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Signature Margherita Pizza',
    description: 'Classic Italian pizza with fresh mozzarella, tomatoes, and basil on a thin, crispy crust, drizzled with extra virgin olive oil.',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&q=80&w=1000',
    category: 'pizza',
    rating: 4.8,
    reviewCount: 124,
    featured: true,
    preparationTime: '15-20 min',
    tags: ['Italian', 'Vegetarian', 'Bestseller'],
    ingredients: ['Fresh Mozzarella', 'San Marzano Tomatoes', 'Fresh Basil', 'Extra Virgin Olive Oil', 'Sea Salt'],
    nutritionalInfo: {
      calories: 285,
      protein: 12,
      carbs: 36,
      fat: 10,
    },
  },
  {
    id: '2',
    name: 'Truffle Mushroom Risotto',
    description: 'Creamy Arborio rice slowly cooked with assorted wild mushrooms, finished with black truffle oil and Parmigiano-Reggiano.',
    price: 18.50,
    image: 'https://images.unsplash.com/photo-1667292182511-b92fa3fa04e9?auto=format&fit=crop&q=80&w=1000',
    category: 'mains',
    rating: 4.9,
    reviewCount: 87,
    featured: true,
    preparationTime: '25-30 min',
    tags: ['Italian', 'Vegetarian', 'Gourmet'],
    ingredients: ['Arborio Rice', 'Wild Mushrooms', 'Truffle Oil', 'Parmigiano-Reggiano', 'White Wine', 'Vegetable Stock'],
    nutritionalInfo: {
      calories: 420,
      protein: 9,
      carbs: 52,
      fat: 18,
    },
  },
  {
    id: '3',
    name: 'Spicy Thai Basil Chicken',
    description: 'Stir-fried minced chicken with Thai basil, chili, and garlic, served with jasmine rice and a fried egg on top.',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=1000',
    category: 'asian',
    rating: 4.7,
    reviewCount: 103,
    featured: true,
    preparationTime: '20-25 min',
    tags: ['Thai', 'Spicy', 'Popular'],
    ingredients: ['Chicken', 'Thai Basil', 'Chili', 'Garlic', 'Jasmine Rice', 'Soy Sauce', 'Fish Sauce', 'Egg'],
    nutritionalInfo: {
      calories: 480,
      protein: 28,
      carbs: 42,
      fat: 22,
    },
  },
  {
    id: '4',
    name: 'Mediterranean Salmon Bowl',
    description: 'Grilled salmon fillet on a bed of quinoa, topped with cucumber, cherry tomatoes, red onion, feta cheese, and tzatziki sauce.',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&q=80&w=1000',
    category: 'healthy',
    rating: 4.6,
    reviewCount: 76,
    featured: true,
    preparationTime: '20 min',
    tags: ['Mediterranean', 'Seafood', 'Healthy'],
    ingredients: ['Wild Salmon', 'Quinoa', 'Cucumber', 'Cherry Tomatoes', 'Red Onion', 'Feta Cheese', 'Greek Yogurt', 'Dill', 'Lemon'],
    nutritionalInfo: {
      calories: 410,
      protein: 32,
      carbs: 28,
      fat: 19,
    },
  },
  {
    id: '5',
    name: 'Classic Beef Burger',
    description: 'Premium ground beef patty with melted cheddar, lettuce, tomato, and special sauce on a toasted brioche bun, served with crispy fries.',
    price: 15.50,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&q=80&w=1000',
    category: 'burgers',
    rating: 4.5,
    reviewCount: 142,
    preparationTime: '15 min',
    tags: ['American', 'Comfort Food', 'Bestseller'],
    ingredients: ['Angus Beef', 'Cheddar Cheese', 'Lettuce', 'Tomato', 'Red Onion', 'Special Sauce', 'Brioche Bun'],
    nutritionalInfo: {
      calories: 680,
      protein: 38,
      carbs: 45,
      fat: 42,
    },
  },
  {
    id: '6',
    name: 'Fresh Berry Açaí Bowl',
    description: 'Blended açaí with banana, topped with granola, fresh strawberries, blueberries, banana slices, and a drizzle of honey.',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1564834744159-ff0ea41ba4b9?auto=format&fit=crop&q=80&w=1000',
    category: 'breakfast',
    rating: 4.7,
    reviewCount: 58,
    preparationTime: '10 min',
    tags: ['Breakfast', 'Healthy', 'Vegetarian'],
    ingredients: ['Açaí', 'Banana', 'Granola', 'Strawberries', 'Blueberries', 'Honey', 'Almond Milk'],
    nutritionalInfo: {
      calories: 320,
      protein: 8,
      carbs: 62,
      fat: 9,
    },
  },
  {
    id: '7',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a molten center, served with vanilla ice cream and a light dusting of powdered sugar.',
    price: 9.50,
    image: 'https://images.unsplash.com/photo-1631778068024-03aa7a327d6e?auto=format&fit=crop&q=80&w=1000',
    category: 'desserts',
    rating: 4.9,
    reviewCount: 93,
    featured: true,
    preparationTime: '15 min',
    tags: ['Dessert', 'Chocolate', 'Indulgent'],
    ingredients: ['Dark Chocolate', 'Butter', 'Eggs', 'Sugar', 'Flour', 'Vanilla Ice Cream'],
    nutritionalInfo: {
      calories: 450,
      protein: 7,
      carbs: 48,
      fat: 28,
    },
  },
  {
    id: '8',
    name: 'Fresh Garden Salad',
    description: 'Crisp mixed greens with cherry tomatoes, cucumber, avocado, red onion, and balsamic vinaigrette dressing.',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?auto=format&fit=crop&q=80&w=1000',
    category: 'salads',
    rating: 4.4,
    reviewCount: 45,
    preparationTime: '10 min',
    tags: ['Healthy', 'Vegetarian', 'Fresh'],
    ingredients: ['Mixed Greens', 'Cherry Tomatoes', 'Cucumber', 'Avocado', 'Red Onion', 'Balsamic Vinaigrette'],
    nutritionalInfo: {
      calories: 220,
      protein: 5,
      carbs: 18,
      fat: 15,
    },
  },
];

export const categories: Category[] = [
  {
    id: '1',
    name: 'Pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=1000',
    count: 12,
  },
  {
    id: '2',
    name: 'Burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=1000',
    count: 8,
  },
  {
    id: '3',
    name: 'Asian',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=1000',
    count: 15,
  },
  {
    id: '4',
    name: 'Healthy',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=1000',
    count: 10,
  },
  {
    id: '5',
    name: 'Desserts',
    image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=1000',
    count: 9,
  },
  {
    id: '6',
    name: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1533089860892-a9b969df67e3?auto=format&fit=crop&q=80&w=1000',
    count: 7,
  },
];
